### ISSUE TITLE
Create a branch that doesn't use Free at all

### ISSUE THREAD

**Issue by natefaubion** [vladciobanu/purescript-halogen-example#6]
`Free` was the only practical way to write instances in 0.11 due to how cumbersome rows were. I think it would be nice to have an example that only uses MTL-style classes and basic instances implemented over something like `ReaderT env Aff` without going through Free. I think Free can be unnecessary for most applications, and certainly for most newcomers.

**Comment by eviefp** [comment]
Thanks! I haven't had time to give too much thought to how this ends up being in 0.12 yet, but I think I should have some time in the next couple of weeks.

I think I have an idea of what you mean, I'll see if I can get something working then.

**Comment by natefaubion** [comment]
I mean specifically something as simple as:

```purescript
type ExampleEnv =
  { navigate :: Route -> Effect Unit
  ...
  }

newtype ExampleM a = ExampleM (ReaderT ExampleEnv Aff a)

instance navigateDSLExampleM :: NavigateDSL ExampleM where
  navigate route = ExampleM do
    env <- ask
    liftEff $ env.navigate route
```

**Comment by thomashoneyman** [comment]
@vladciobanu If you're interested in pull requests I can implement this and submit it as a PR.

**Comment by eviefp** [comment]
Thank you again for the 0.12 PR. I think the two remaining things to do right now are @natefaubion 's suggestion of removing `Free` and updating the `README`. If you want to also take a stab at removing `Free`, go ahead. 

If not, I should have time either this weekend or early next week to work on it myself. Let me know. :)

**Comment by thomashoneyman** [comment]
Solved by https://github.com/vladciobanu/purescript-halogen-example/pull/8

**Comment by thomashoneyman** [comment]
We could probably close this one :)
